name: Changelog Reminder

on: pull_request

jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Changelog Reminder
        uses: peterjgrainger/action-changelog-reminder@v1
        with:
          changelog_regex: '/CHANGELOG.md'
          customPrMessage: "We couldn't find any modification to the CHANGELOG.md file. If your changes are not suitable for the changelog, that's fine. Otherwise please add them to the changelog!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
